# docker-compose.yml
services:
  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      
    ports:
      - "3000:3000"
      - "5555:5555"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/scottys_reviews
      NEXTAUTH_SECRET: your-super-secret
    volumes:
      - .:/app
      - /app/node_modules
    command: sh ./start.sh

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scottys_reviews
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

