name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  docker-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and start services with Docker Compose
        run: |
          docker compose up --build -d
          
      - name: Wait for services to be ready
        run: |
          echo "Waiting for database to be ready..."
          timeout 90 bash -c 'until docker compose exec -T db pg_isready -U postgres; do sleep 2; done'
          echo "Waiting for app to start..."
          sleep 30
          echo "Checking if app is responding..."
          timeout 30 bash -c 'until curl -f http://localhost:3000/api/courses/search?q=test || true; do sleep 2; done'

      - name: Run tests in Docker
        run: |
          docker compose exec -T app npm test

      # - name: Test build in Docker
      #   run: |
      #     docker compose exec -T app npm run build

      - name: Clean up
        if: always()
        run: |
          docker compose down -v